### ISSUE TITLE
Compilation fails with Clang 4.0.1-6 on Ubuntu 17.10

### ISSUE THREAD

**Issue by RauliL** [RauliL/raxvt#7]
When attempting to compile with Clang 4.0.1-6, the GLib version check macro fails for some reason. GLib version is 2.54.1 on Ubuntu 17.10.

```
make[1]: Entering directory '/home/rauli/project/raxvt/src'
clang++ -I.. -I. -I. -I./../libev -I./../libptytty/src -I./../tinytoml/include -DHAVE_CONFIG_H -I/usr/include/freetype2  -Wall -Werror -std=c++11 -w  -c main.cpp
main.cpp:580:39: error: token is not a valid binary operator in a preprocessor subexpression
#if HAVE_PIXBUF && !GLIB_CHECK_VERSION(2, 35, 0)
                   ~~~~~~~~~~~~~~~~~~~^
1 error generated.
Makefile:56: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
make[1]: Leaving directory '/home/rauli/project/raxvt/src'
Makefile:31: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by RauliL** [comment]
Seems to be no longer an issue.
